{
 "title": "Aztecscan Sandbox Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "L2-block finalization status",
   "type": "stat",
   "description": "TODO: automate translation of finalization-status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    lfs.l2_block_hash,\n    lfs.\"timestamp\",\n    lb.height as l2_seen_proposed\nFROM \"l2BlockFinalizationStatus\" lfs\nLEFT JOIN \"l2Block\" lb ON lfs.l2_block_hash = lb.hash\nWHERE lfs.status = 0\nORDER BY lfs.\"timestamp\" DESC\nLIMIT 50"
    },
    {
     "rawSql": "SELECT \n    lfs.l2_block_hash,\n    lfs.\"timestamp\",\n    lb.height as l2_seen_proven\nFROM \"l2BlockFinalizationStatus\" lfs\nLEFT JOIN \"l2Block\" lb ON lfs.l2_block_hash = lb.hash\nWHERE lfs.status = 1\nORDER BY lfs.\"timestamp\" DESC\nLIMIT 50"
    },
    {
     "rawSql": "SELECT \n    lfs.l2_block_hash,\n    lfs.\"timestamp\",\n    lb.height as l1_seen_proposed\nFROM \"l2BlockFinalizationStatus\" lfs\nLEFT JOIN \"l2Block\" lb ON lfs.l2_block_hash = lb.hash\nWHERE lfs.status = 2\nORDER BY lfs.\"timestamp\" DESC\nLIMIT 50"
    },
    {
     "rawSql": "SELECT \n    lfs.l2_block_hash,\n    lfs.\"timestamp\",\n    lb.height as l1_seen_proven\nFROM \"l2BlockFinalizationStatus\" lfs\nLEFT JOIN \"l2Block\" lb ON lfs.l2_block_hash = lb.hash\nWHERE lfs.status = 3\nORDER BY lfs.\"timestamp\" DESC\nLIMIT 50"
    },
    {
     "rawSql": "SELECT \n    lfs.l2_block_hash,\n    lfs.\"timestamp\",\n    lb.height as l1_mined_proposed\nFROM \"l2BlockFinalizationStatus\" lfs\nLEFT JOIN \"l2Block\" lb ON lfs.l2_block_hash = lb.hash\nWHERE lfs.status = 4\nORDER BY lfs.\"timestamp\" DESC\nLIMIT 50"
    },
    {
     "rawSql": "SELECT \n    lfs.l2_block_hash,\n    lfs.\"timestamp\",\n    lb.height as l1_mined_proven\nFROM \"l2BlockFinalizationStatus\" lfs\nLEFT JOIN \"l2Block\" lb ON lfs.l2_block_hash = lb.hash\nWHERE lfs.status = 5\nORDER BY lfs.\"timestamp\" DESC\nLIMIT 50"
    }
   ]
  },
  {
   "title": "L1 block finalization status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  l1_block_number as finalized_height,\n  to_timestamp(l1_block_timestamp) AS timestamp_date,\n  is_finalized\nFROM l1_generic_contract_event\nWHERE is_finalized IS TRUE\nORDER BY l1_block_timestamp DESC LIMIT 50"
    },
    {
     "rawSql": "SELECT\n  l1_block_number as pending_height,\n  to_timestamp(l1_block_timestamp) AS timestamp_date,\n  is_finalized\nFROM l1_generic_contract_event\nWHERE is_finalized IS FALSE\nORDER BY l1_block_timestamp DESC LIMIT 50"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"l1BlockNumber\", \"l2BlockNumber\", \"l1BlockTimestamp\" AS \"time\" FROM \"l1L2BlockProposed\" ORDER BY \"l1BlockTimestamp\" DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Latest L1-events",
   "type": "table",
   "description": "(limit 50)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH events AS (\n    SELECT \n        event_name, \n        l1_block_number,\n        to_timestamp(l1_block_timestamp) AS timestamp_date\n    FROM l1_generic_contract_event\n)\nSELECT event_name, l1_block_number,\n  COALESCE(\n    CASE \n      WHEN timestamp_date IS NULL\n      THEN 'NOT SEEN'\n\n      WHEN age(NOW(), timestamp_date) < interval '0 minute' \n      THEN 'future!'\n\n      WHEN age(NOW(), timestamp_date) < interval '1 hour' \n      THEN concat(extract(minute from age(NOW(), timestamp_date)), ' minutes ago')\n\n      WHEN age(NOW(), timestamp_date) < interval '1 day'\n      THEN concat(extract(hour from age(NOW(), timestamp_date)), ' hours ago')\n\n      ELSE concat(extract(day from age(NOW(), timestamp_date)), ' days ago')\n    END, \n    'NOT SEEN'\n  ) AS last_seen_readable,\n  timestamp_date\nFROM events\nORDER BY timestamp_date DESC LIMIT 50\n"
    }
   ]
  }
 ]
}