/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ContractsLazyImport = createFileRoute('/contracts')()
const IndexLazyImport = createFileRoute('/')()
const TransactionsIndexLazyImport = createFileRoute('/transactions/')()
const BlocksIndexLazyImport = createFileRoute('/blocks/')()
const TransactionsTransactionIdLazyImport = createFileRoute(
  '/transactions/$transactionId',
)()
const BlocksBlockNumberLazyImport = createFileRoute('/blocks/$blockNumber')()

// Create/Update Routes

const ContractsLazyRoute = ContractsLazyImport.update({
  path: '/contracts',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/contracts.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TransactionsIndexLazyRoute = TransactionsIndexLazyImport.update({
  path: '/transactions/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/transactions/index.lazy').then((d) => d.Route),
)

const BlocksIndexLazyRoute = BlocksIndexLazyImport.update({
  path: '/blocks/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/blocks/index.lazy').then((d) => d.Route))

const TransactionsTransactionIdLazyRoute =
  TransactionsTransactionIdLazyImport.update({
    path: '/transactions/$transactionId',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/transactions/$transactionId.lazy').then((d) => d.Route),
  )

const BlocksBlockNumberLazyRoute = BlocksBlockNumberLazyImport.update({
  path: '/blocks/$blockNumber',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/blocks/$blockNumber.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsLazyImport
      parentRoute: typeof rootRoute
    }
    '/blocks/$blockNumber': {
      id: '/blocks/$blockNumber'
      path: '/blocks/$blockNumber'
      fullPath: '/blocks/$blockNumber'
      preLoaderRoute: typeof BlocksBlockNumberLazyImport
      parentRoute: typeof rootRoute
    }
    '/transactions/$transactionId': {
      id: '/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof TransactionsTransactionIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ContractsLazyRoute,
  BlocksBlockNumberLazyRoute,
  TransactionsTransactionIdLazyRoute,
  BlocksIndexLazyRoute,
  TransactionsIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contracts",
        "/blocks/$blockNumber",
        "/transactions/$transactionId",
        "/blocks/",
        "/transactions/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/contracts": {
      "filePath": "contracts.lazy.tsx"
    },
    "/blocks/$blockNumber": {
      "filePath": "blocks/$blockNumber.lazy.tsx"
    },
    "/transactions/$transactionId": {
      "filePath": "transactions/$transactionId.lazy.tsx"
    },
    "/blocks/": {
      "filePath": "blocks/index.lazy.tsx"
    },
    "/transactions/": {
      "filePath": "transactions/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
